name: random_country
description: "Random Country App"
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.1.1 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.0
  http: ^1.1.0
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^5.0.2
  flutter_launcher_icons: ^0.14.3
  shared_preferences: ^2.0.6
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  flutter_native_splash: ^2.3.9

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo.png

flutter_native_splash:
  color: "#ffffff"
  image: "assets/logo.png"
  color_dark: "#121212"
  image_dark: "assets/logo.png"
  android: true
  ios: true
  web: false
  fullscreen: true

# Configuration pour les icônes d'application
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo.png"
  remove_alpha_ios: true
